/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.penjualan;

import config.Koneksi;
import dao.AkunDAO;
import dao.ProdukDAO;
import dao.ProdukRestokDAO;
import helper.DatePickerHelper;
import helper.KodeTransaksi;
import helper.NomorTransaksi;
import helper.RupiahFormat;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import model.Akun;
import model.Produk;
import model.ProdukRestok;
import raven.datetime.DatePicker;
import session.Session;
import view.main.MainFrame;

/**
 *
 * @author ASUS
 */
public
        class Restok extends javax.swing.JPanel {

    
    private DatePicker DpTgl;
    
    /**
     * Creates new form Restok
     */
    public
            Restok() {
        initComponents();
        inisialisasiRestok();
        
        DpTgl = DatePickerHelper.install(
            TxtTgl,
            LocalDate.now(),
            Color.WHITE
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BtnBack = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        Form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtNoTransaksi = new javax.swing.JTextField();
        TxtTgl = new javax.swing.JFormattedTextField();
        TxtIdProduk = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtQty = new javax.swing.JSpinner();
        TxtHargaBeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtNote = new javax.swing.JTextArea();
        BtnAdd = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CbAkun = new javax.swing.JComboBox<>();
        TxtTotal = new javax.swing.JTextField();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbRestok = new javax.swing.JTable();
        BtnHist = new javax.swing.JButton();
        BtnData = new javax.swing.JButton();

        BtnBack.setText("Kembali");
        BtnBack.setName("BtnBack"); // NOI18N
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        Form.setBackground(new java.awt.Color(255, 255, 255));
        Form.setName("Form"); // NOI18N
        Form.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ID");
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel1, gridBagConstraints);

        jLabel2.setText("No. Transaksi");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Tanggal");
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel3, gridBagConstraints);

        jLabel5.setText("ID Produk");
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Nama Produk");
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Qty");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Harga beli");
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Total");
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Catatan");
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        Form.add(jLabel10, gridBagConstraints);

        TxtId.setEditable(false);
        TxtId.setEnabled(false);
        TxtId.setFocusable(false);
        TxtId.setName("TxtId"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtId, gridBagConstraints);

        TxtNoTransaksi.setEditable(false);
        TxtNoTransaksi.setEnabled(false);
        TxtNoTransaksi.setFocusable(false);
        TxtNoTransaksi.setName("TxtNoTransaksi"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtNoTransaksi, gridBagConstraints);

        TxtTgl.setName("TxtTgl"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtTgl, gridBagConstraints);

        TxtIdProduk.setName("TxtIdProduk"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtIdProduk, gridBagConstraints);

        TxtNama.setName("TxtNama"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtNama, gridBagConstraints);

        TxtQty.setName("TxtQty"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtQty, gridBagConstraints);

        TxtHargaBeli.setName("TxtHargaBeli"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtHargaBeli, gridBagConstraints);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        TxtNote.setColumns(20);
        TxtNote.setRows(5);
        TxtNote.setName("TxtNote"); // NOI18N
        jScrollPane1.setViewportView(TxtNote);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(jScrollPane1, gridBagConstraints);

        BtnAdd.setText("Tambah");
        BtnAdd.setName("BtnAdd"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        Form.add(BtnAdd, gridBagConstraints);

        BtnClear.setText("Cancel");
        BtnClear.setName("BtnClear"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        Form.add(BtnClear, gridBagConstraints);

        jLabel11.setText("Akun");
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 7);
        Form.add(jLabel11, gridBagConstraints);

        CbAkun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "BRI" }));
        CbAkun.setName("CbAkun"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 7, 7);
        Form.add(CbAkun, gridBagConstraints);

        TxtTotal.setName("TxtTotal"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        Form.add(TxtTotal, gridBagConstraints);

        BtnUpdate.setText("Update");
        BtnUpdate.setName("BtnUpdate"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        Form.add(BtnUpdate, gridBagConstraints);

        BtnDelete.setText("Delete");
        BtnDelete.setName("BtnDelete"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        Form.add(BtnDelete, gridBagConstraints);

        jSplitPane1.setRightComponent(Form);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        TbRestok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbRestok.setName("TbRestok"); // NOI18N
        jScrollPane2.setViewportView(TbRestok);

        jSplitPane1.setLeftComponent(jScrollPane2);

        BtnHist.setText("Riwayat");
        BtnHist.setName("BtnHist"); // NOI18N
        BtnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHistActionPerformed(evt);
            }
        });

        BtnData.setText("Data Produk");
        BtnData.setName("BtnData"); // NOI18N
        BtnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnHist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnData)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack)
                    .addComponent(BtnHist)
                    .addComponent(BtnData))
                .addGap(6, 6, 6)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.PenjualanContainer.getLayout();
        cl.show(MainFrame.PenjualanContainer, "HOME");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.PenjualanContainer.getLayout();
        cl.show(MainFrame.PenjualanContainer, "RIWAYAT");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHistActionPerformed

    private void BtnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.PenjualanContainer.getLayout();
        cl.show(MainFrame.PenjualanContainer, "DATA");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDataActionPerformed


    private final ProdukDAO produkDAO = new ProdukDAO();
    private final AkunDAO akunDAO = new AkunDAO();
    private final ProdukRestokDAO produkRestokDAO = new ProdukRestokDAO();
    private final Map<String, Produk> produkComboMap = new LinkedHashMap<>();
    private final Map<String, Akun> akunComboMap = new LinkedHashMap<>();

    private void inisialisasiRestok() {
        TxtId.setEditable(false);
        TxtNoTransaksi.setEditable(false);
        TxtIdProduk.setEditable(false);
        TxtNama.setEditable(false);
        TxtHargaBeli.setEditable(false);
        TxtTgl.setEditable(false);
        TxtQty.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);

        jComboBox2.addActionListener(e -> pilihProduk());
        TxtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formatTotalHarga();
            }
        });
        reloadDataForm();
    }

    private void reloadDataForm() {
        loadComboProduk();
        loadComboAkun();
        resetForm();
    }

    private void loadComboProduk() {
        produkComboMap.clear();
        jComboBox2.removeAllItems();
        jComboBox2.addItem("-- Pilih Produk --");
        List<Produk> daftarProduk = produkDAO.getAllProduk("");
        for (Produk produk : daftarProduk) {
            String label = produk.getNamaProduk() + " (" + produk.getKodeProduk() + ") - ID " + produk.getIdProduk();
            produkComboMap.put(label, produk);
            jComboBox2.addItem(label);
        }
    }

    private void loadComboAkun() {
        akunComboMap.clear();
        CbAkun.removeAllItems();
        CbAkun.addItem("-- Pilih Akun --");
        for (Akun akun : akunDAO.getAllAkun()) {
            String label = akun.getNamaAkun() + " - ID " + akun.getIdAkun();
            akunComboMap.put(label, akun);
            CbAkun.addItem(label);
        }
    }

    private void pilihProduk() {
        Produk produk = getProdukTerpilih();
        if (produk == null) {
            TxtIdProduk.setText("");
            TxtNama.setText("");
            TxtHargaBeli.setText("");
            return;
        }
        TxtIdProduk.setText(String.valueOf(produk.getIdProduk()));
        TxtNama.setText(produk.getNamaProduk());
        TxtHargaBeli.setText(RupiahFormat.format(produk.getHargaBeli()));
    }

    private Produk getProdukTerpilih() {
        Object item = jComboBox2.getSelectedItem();
        return item == null ? null : produkComboMap.get(item.toString());
    }

    private Akun getAkunTerpilih() {
        Object item = CbAkun.getSelectedItem();
        return item == null ? null : akunComboMap.get(item.toString());
    }

    private void resetForm() {
        TxtId.setText("");
        TxtNoTransaksi.setText(NomorTransaksi.generate(KodeTransaksi.RESTOK_PRODUK, "tb_produk_restok"));
        TxtTgl.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
        if (jComboBox2.getItemCount() > 0) {
            jComboBox2.setSelectedIndex(0);
        }
        if (CbAkun.getItemCount() > 0) {
            CbAkun.setSelectedIndex(0);
        }
        TxtQty.setValue(1);
        TxtTotal.setText("");
        TxtNote.setText("");
        isiTabelKosong();
    }

    private void isiTabelKosong() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"No Transaksi", "Tanggal", "Produk", "Qty", "Total"}, 0);
        TbRestok.setModel(model);
    }

    private void formatTotalHarga() {
        double total = RupiahFormat.parse(TxtTotal.getText());
        if (total > 0) {
            TxtTotal.setText(RupiahFormat.format(total));
        }
    }

    private void tambahRestok() {
        Produk produkPilihan = getProdukTerpilih();
        Akun akunPilihan = getAkunTerpilih();
        int qty = ((Number) TxtQty.getValue()).intValue();
        double total = RupiahFormat.parse(TxtTotal.getText());

        if (produkPilihan == null) {
            JOptionPane.showMessageDialog(this, "Produk wajib dipilih.");
            return;
        }
        if (akunPilihan == null) {
            JOptionPane.showMessageDialog(this, "Akun wajib dipilih.");
            return;
        }
        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Qty harus lebih dari 0.");
            return;
        }
        if (total <= 0) {
            JOptionPane.showMessageDialog(this, "Total harga harus lebih dari 0.");
            return;
        }
        if (Session.idUser <= 0) {
            JOptionPane.showMessageDialog(this, "Session user tidak valid. Silakan login ulang.");
            return;
        }

        try (Connection conn = Koneksi.getConnection()) {
            conn.setAutoCommit(false);
            try {
                double saldo = akunDAO.getSaldo(conn, akunPilihan.getIdAkun());
                if (saldo < total) {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, "Saldo akun tidak cukup.");
                    return;
                }

                Produk produkDb = produkDAO.getProdukById(conn, produkPilihan.getIdProduk());
                if (produkDb == null) {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
                    return;
                }

                double hargaBeliBaru = total / qty;
                int stokLama = produkDb.getStok();
                double hargaBeliLama = produkDb.getHargaBeli();
                double hargaBeliRataRata = ((stokLama * hargaBeliLama) + (qty * hargaBeliBaru)) / (stokLama + qty);

                ProdukRestok restok = new ProdukRestok();
                restok.setNomorTransaksi(TxtNoTransaksi.getText());
                restok.setTanggal(Date.valueOf(LocalDate.now()));
                restok.setUserId(Session.idUser);
                restok.setProdukId(produkDb.getIdProduk());
                restok.setAkunId(akunPilihan.getIdAkun());
                restok.setQty(qty);
                restok.setHargaBeli(hargaBeliBaru);
                restok.setTotal(total);
                restok.setCatatan(TxtNote.getText());

                if (!produkRestokDAO.tambahRestok(conn, restok)) {
                    throw new Exception("Gagal menyimpan transaksi restok.");
                }
                if (!produkDAO.tambahStokDanUpdateHargaBeli(conn, produkDb.getIdProduk(), qty, hargaBeliRataRata)) {
                    throw new Exception("Gagal menambah stok produk.");
                }
                if (!akunDAO.kurangiSaldo(conn, akunPilihan.getIdAkun(), total)) {
                    throw new Exception("Gagal mengurangi saldo akun.");
                }

                conn.commit();
                JOptionPane.showMessageDialog(this, "Restok produk berhasil disimpan.");
                reloadDataForm();
            } catch (Exception e) {
                conn.rollback();
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Koneksi database gagal: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnData;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnHist;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CbAkun;
    private javax.swing.JPanel Form;
    private javax.swing.JTable TbRestok;
    private javax.swing.JTextField TxtHargaBeli;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtIdProduk;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNoTransaksi;
    private javax.swing.JTextArea TxtNote;
    private javax.swing.JSpinner TxtQty;
    private javax.swing.JFormattedTextField TxtTgl;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
