/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.brilink;

/**
 *
 * @author ASUS
 */
public
        class BRILinkPanel extends javax.swing.JPanel {


    public
            BRILinkPanel() {
        initComponents();
        BriCard.putClientProperty(
                "FlatLaf.style",
                "arc:20" );
        CashCard.putClientProperty(
                "FlatLaf.style",
                "arc:20" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CashCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saldoCash = new javax.swing.JLabel();
        BriCard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        saldoCash1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));

        CashCard.setBackground(new java.awt.Color(51, 153, 0));
        CashCard.setName("CashCard"); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Saldo Cash");
        jLabel3.setName("jLabel3"); // NOI18N

        saldoCash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saldoCash.setForeground(new java.awt.Color(255, 255, 255));
        saldoCash.setText("Rp 4.300.000");
        saldoCash.setName("saldoCash"); // NOI18N

        javax.swing.GroupLayout CashCardLayout = new javax.swing.GroupLayout(CashCard);
        CashCard.setLayout(CashCardLayout);
        CashCardLayout.setHorizontalGroup(
            CashCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CashCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(CashCardLayout.createSequentialGroup()
                        .addComponent(saldoCash, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        CashCardLayout.setVerticalGroup(
            CashCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(saldoCash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BriCard.setBackground(new java.awt.Color(0, 102, 255));
        BriCard.setName("BriCard"); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo BRI");
        jLabel4.setName("jLabel4"); // NOI18N

        saldoCash1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saldoCash1.setForeground(new java.awt.Color(255, 255, 255));
        saldoCash1.setText("Rp 2.300.000");
        saldoCash1.setName("saldoCash1"); // NOI18N

        javax.swing.GroupLayout BriCardLayout = new javax.swing.GroupLayout(BriCard);
        BriCard.setLayout(BriCardLayout);
        BriCardLayout.setHorizontalGroup(
            BriCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BriCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(BriCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(BriCardLayout.createSequentialGroup()
                        .addComponent(saldoCash1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGap(0, 0, 0))
        );
        BriCardLayout.setVerticalGroup(
            BriCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BriCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(saldoCash1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BriCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CashCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CashCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BriCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BriCard;
    private javax.swing.JPanel CashCard;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel saldoCash;
    private javax.swing.JLabel saldoCash1;
    // End of variables declaration//GEN-END:variables
}
