/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.brilink;

import dao.KategoriTopupDAO;
import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KategoriTopup;
import view.main.MainFrame;

/**
 *
 * @author ASUS
 */
public
        class Kategori extends javax.swing.JPanel {

    private final KategoriTopupDAO kategoriDAO = new KategoriTopupDAO();

    /**
     * Creates new form Kategori
     */
    public
            Kategori() {
        initComponents();
        TxtID.setEditable(false);
        initActions();
        loadKategori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        TxtNamaKategori = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        BtnHist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.4);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ID");
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nama Kategori");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        TxtID.setName("TxtID"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(TxtID, gridBagConstraints);

        TxtNamaKategori.setName("TxtNamaKategori"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(TxtNamaKategori, gridBagConstraints);

        BtnAdd.setText("Tambah");
        BtnAdd.setName("BtnAdd"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnAdd, gridBagConstraints);

        BtnDelete.setText("Delete");
        BtnDelete.setName("BtnDelete"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnDelete, gridBagConstraints);

        BtnClear.setText("Cancel");
        BtnClear.setName("BtnClear"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnClear, gridBagConstraints);

        BtnUpdate.setText("Update");
        BtnUpdate.setName("BtnUpdate"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnUpdate, gridBagConstraints);

        BtnBack.setText("Kembali");
        BtnBack.setName("BtnBack"); // NOI18N
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnBack, gridBagConstraints);

        BtnHist.setText("Riwayat");
        BtnHist.setName("BtnHist"); // NOI18N
        BtnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHistActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnHist, gridBagConstraints);

        jSplitPane1.setTopComponent(jPanel1);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initActions() {
        BtnAdd.addActionListener(e -> tambahKategori());
        BtnUpdate.addActionListener(e -> updateKategori());
        BtnDelete.addActionListener(e -> deleteKategori());
        BtnClear.addActionListener(e -> clearForm());
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                int row = jTable1.getSelectedRow();
                TxtID.setText(jTable1.getValueAt(row, 0).toString());
                TxtNamaKategori.setText(jTable1.getValueAt(row, 1).toString());
            }
        });
    }

    private void loadKategori() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nama Kategori"}, 0) {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        for (KategoriTopup k : kategoriDAO.getAll()) model.addRow(new Object[]{k.getIdKategori(), k.getNamaKategori()});
        jTable1.setModel(model);
    }

    private void tambahKategori() {
        String nama = TxtNamaKategori.getText().trim();
        if (nama.isEmpty()) { JOptionPane.showMessageDialog(this, "Nama kategori wajib diisi."); return; }
        if (kategoriDAO.isDuplicate(nama)) { JOptionPane.showMessageDialog(this, "Nama kategori sudah ada."); return; }
        kategoriDAO.insert(new KategoriTopup(0, nama));
        JOptionPane.showMessageDialog(this, "Kategori berhasil ditambahkan.");
        clearForm(); loadKategori();
    }

    private void updateKategori() {
        if (TxtID.getText().trim().isEmpty()) { JOptionPane.showMessageDialog(this, "Pilih kategori yang akan diupdate."); return; }
        String nama = TxtNamaKategori.getText().trim();
        if (nama.isEmpty()) { JOptionPane.showMessageDialog(this, "Nama kategori wajib diisi."); return; }
        KategoriTopup existing = kategoriDAO.findById(Integer.parseInt(TxtID.getText()));
        if (existing != null && !existing.getNamaKategori().equalsIgnoreCase(nama) && kategoriDAO.isDuplicate(nama)) { JOptionPane.showMessageDialog(this, "Nama kategori sudah ada."); return; }
        kategoriDAO.update(new KategoriTopup(Integer.parseInt(TxtID.getText()), nama));
        JOptionPane.showMessageDialog(this, "Kategori berhasil diupdate.");
        clearForm(); loadKategori();
    }

    private void deleteKategori() {
        if (TxtID.getText().trim().isEmpty()) { JOptionPane.showMessageDialog(this, "Pilih kategori yang akan dihapus."); return; }
        if (JOptionPane.showConfirmDialog(this, "Hapus kategori ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
        try {
            kategoriDAO.delete(Integer.parseInt(TxtID.getText()));
            JOptionPane.showMessageDialog(this, "Kategori berhasil dihapus.");
            clearForm(); loadKategori();
        } catch (RuntimeException e) {
            Throwable cause = e.getCause();
            if (cause instanceof SQLException) JOptionPane.showMessageDialog(this, "Kategori tidak dapat dihapus karena masih dipakai transaksi BRILink.");
            else JOptionPane.showMessageDialog(this, "Gagal menghapus kategori: " + e.getMessage());
        }
    }

    private void clearForm() { TxtID.setText(""); TxtNamaKategori.setText(""); jTable1.clearSelection(); }

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.BRILinkContainer.getLayout();
        cl.show(MainFrame.BRILinkContainer, "HOME");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.BRILinkContainer.getLayout();
        cl.show(MainFrame.BRILinkContainer, "RIWAYAT");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHistActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnHist;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtNamaKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
