#
# GLOBAL
#
defaultFont = 13 "Poppins"
Label.font = 12 "Poppins"
Component.arc=12
Component.arrowType=triangle
Panel.arc=12
TextComponent.arc=12
Button.arc=12
ScrollBar.width=8

#
# COLOR
#
@baseColor=#FFFFFF
@accentColor=#000000
@cashColor=#009900
@briColor=#0466c8
@bbmColor=#FF0000

#
# BUTTON
#

Button.focusWidth=1
Button.innerFocusWidth=0
Button.borderWidth=0

#
# TEXT FIELD
#

TextField.showClearButton=true

SplitPaneDivider.oneTouchArrowColor=#000000

PasswordField.showRevealButton:true





#
# TABLE
#

Table.showHorizontalLines=false
Table.showVerticalLines=false
Table.rowHeight=32

#
# SCROLLBAR
#

ScrollBar.thumbArc=999
ScrollBar.trackArc=999

#
# COMBOBOX
#

ComboBox.padding=4,8,4,8
ComboBox.selectionBackground=@briColor
ComboBox.buttonArrowColor=@briColor

#
# PANEL
#

Panel.background=#f2f2f2



Button.background=@accentColor
Button.foreground=#FFFFFF

TabbedPane.underlineColor=@accentColor
TabbedPane.inactiveUnderlineColor=@accentColor
TabbedPane.selectedForeground=@accentColor
TabbedPane.foreground=#808080
TabbedPane.tabAlignment=leading
TabbedPane.selectedBackground=#ffffff
TabbedPane.tabType=underlined
TabbedPane.tabHeight=30
TabbedPane.tabSelectionHeight=4
TabbedPane.tabSelectionArc=200
TabbedPane.contentAreaColor=#ffffff
TabbedPane.showTabSeparators=false

PopupMenu.borderColor=#f0f0f0
PopupMenu.borderCornerRadius=999

[style].briButton=arc:12;borderWidth:2;borderColor:@briColor;background:@briColor;foreground:@baseColor;
[style].basePanel=arc:16;background:@baseColor;
