#
# GLOBAL
#

Component.arc=12
Panel.arc=12
TextComponent.arc=12
Button.arc=12
ScrollBar.width=8

#
# BUTTON
#

Button.focusWidth=1
Button.innerFocusWidth=0

#
# TEXT FIELD
#

TextField.showClearButton=true

#
# TABBED PANE
#

TabbedPane.tabHeight=50
TabbedPane.showTabSeparators=false

#
# TABLE
#

Table.showHorizontalLines=false
Table.showVerticalLines=false
Table.rowHeight=32

#
# SCROLLBAR
#

ScrollBar.thumbArc=999
ScrollBar.trackArc=999

#
# COMBOBOX
#

ComboBox.padding=4,8,4,8

#
# PANEL
#

Panel.background=#F8F9FA

#
# COLOR
#

@accentColor=#000000

Button.background=@accentColor
Button.foreground=#FFFFFF

TabbedPane.selectedBackground=@accentColor
TabbedPane.selectedForeground=#FFFFFF
TabbedPane.hoverColor=@accentColor
TabbedPane.hoverForeground=#FFFFFF

