/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.bbm;

import helper.UiThemeUtil;
import dao.BBMDAO;
import helper.DatePickerHelper;
import java.awt.CardLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BBM;
import model.BBMPenjualan;
import session.Session;
import raven.datetime.DatePicker;
import view.main.MainFrame;

/**
 *
 * @author ASUS
 */
public
        class Riwayat extends javax.swing.JPanel {

    /**
     * Creates new form Riwayat
     */
    public
            Riwayat() {
        initComponents();
        UiThemeUtil.styleNamedTables(this, "arc: 12", "Tb");
        setupPenjualanBBM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        TxtHargaJual = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();
        TxtDiterima = new javax.swing.JTextField();
        TxtKembalian = new javax.swing.JTextField();
        TxtPembayaran = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnUpdate = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        TxtNoTransaksi = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtLiter = new javax.swing.JTextField();
        TxtTgl = new javax.swing.JFormattedTextField();
        BtnBack = new javax.swing.JButton();
        BtnRestok = new javax.swing.JButton();
        BtnData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbRiwayat = new javax.swing.JTable();
        BtnDelete = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        TxtHargaJual.setName("TxtHargaJual"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 5);
        jPanel1.add(TxtHargaJual, gridBagConstraints);

        TxtTotal.setName("TxtTotal"); // NOI18N
        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 5);
        jPanel1.add(TxtTotal, gridBagConstraints);

        TxtDiterima.setName("TxtDiterima"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel1.add(TxtDiterima, gridBagConstraints);

        TxtKembalian.setName("TxtKembalian"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 5);
        jPanel1.add(TxtKembalian, gridBagConstraints);

        TxtPembayaran.setName("TxtPembayaran"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 5);
        jPanel1.add(TxtPembayaran, gridBagConstraints);

        jLabel1.setText("Harga Jual");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Total");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Pembayaran");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Diterima");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel6.setText("Kembalian");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 5);
        jPanel1.add(jLabel6, gridBagConstraints);

        BtnUpdate.setBackground(new java.awt.Color(255, 0, 0));
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setName("BtnUpdate"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnUpdate, gridBagConstraints);

        BtnClear.setBackground(new java.awt.Color(0, 0, 0));
        BtnClear.setForeground(new java.awt.Color(255, 255, 255));
        BtnClear.setText("Cancel");
        BtnClear.setName("BtnClear"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnClear, gridBagConstraints);

        jLabel7.setText("ID");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("No. Transaksi");
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Tanggal");
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Nama BBM");
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Liter");
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jLabel11, gridBagConstraints);

        TxtID.setEditable(false);
        TxtID.setFocusable(false);
        TxtID.setName("TxtID"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 6, 6);
        jPanel1.add(TxtID, gridBagConstraints);

        TxtNoTransaksi.setEditable(false);
        TxtNoTransaksi.setEnabled(false);
        TxtNoTransaksi.setName("TxtNoTransaksi"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel1.add(TxtNoTransaksi, gridBagConstraints);

        TxtNama.setName("TxtNama"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel1.add(TxtNama, gridBagConstraints);

        TxtLiter.setName("TxtLiter"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel1.add(TxtLiter, gridBagConstraints);

        TxtTgl.setName("TxtTgl"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel1.add(TxtTgl, gridBagConstraints);

        BtnBack.setText("<- Kembali");
        BtnBack.setMargin(new java.awt.Insets(2, 0, 3, 14));
        BtnBack.setName("BtnBack"); // NOI18N
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnBack, gridBagConstraints);

        BtnRestok.setBackground(new java.awt.Color(255, 0, 0));
        BtnRestok.setForeground(new java.awt.Color(255, 255, 255));
        BtnRestok.setText("Restok BBM");
        BtnRestok.setName("BtnRestok"); // NOI18N
        BtnRestok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestokActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnRestok, gridBagConstraints);

        BtnData.setBackground(new java.awt.Color(255, 0, 0));
        BtnData.setForeground(new java.awt.Color(255, 255, 255));
        BtnData.setText("Data BBM");
        BtnData.setName("BtnData"); // NOI18N
        BtnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnData, gridBagConstraints);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        TbRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbRiwayat.setName("TbRiwayat"); // NOI18N
        jScrollPane2.setViewportView(TbRiwayat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        BtnDelete.setText("Delete");
        BtnDelete.setName("BtnDelete"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(BtnDelete, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.BBMContainer.getLayout();
        cl.show(MainFrame.BBMContainer, "HOME");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed

    private void BtnRestokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestokActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.BBMContainer.getLayout();
        cl.show(MainFrame.BBMContainer, "RESTOK");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRestokActionPerformed

    private void BtnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataActionPerformed
        CardLayout cl =
        (CardLayout) MainFrame.BBMContainer.getLayout();
        cl.show(MainFrame.BBMContainer, "DATA");
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDataActionPerformed

    private final BBMDAO bbmDAO = new BBMDAO();
    private final JComboBox<String> comboMetodePembayaran = new JComboBox<>();
    private DatePicker DpTgl;
    private int selectedBbmId = 0;
    private int selectedHistoryId = 0;
    private String modeTabel = "DATA";

    private void setupPenjualanBBM() {
        BtnUpdate.setText("Simpan Penjualan");
        BtnClear.setText("Clear");
        TxtID.setEditable(false);
        TxtNama.setEditable(false);
        TxtTotal.setEditable(false);
        TxtKembalian.setEditable(false);
        DpTgl = DatePickerHelper.install(TxtTgl);
        setupMetodePembayaran();
        setupTombolRiwayat();
        BtnUpdate.addActionListener(e -> simpanPenjualan());
        BtnClear.addActionListener(e -> clearForm());
        TbRiwayat.addMouseListener(new java.awt.event.MouseAdapter() { public void mouseClicked(java.awt.event.MouseEvent evt) { pilihBarisTabel(); } });
        TbRiwayat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) hapusRiwayatTerpilih();
            }
        });
        tampilBBM();
    }

    private void setupMetodePembayaran() {
        TxtPembayaran.setVisible(false);
        comboMetodePembayaran.setName("comboMetodePembayaranBBM");
        comboMetodePembayaran.removeAllItems();
        comboMetodePembayaran.addItem("Cash");
        comboMetodePembayaran.addItem("BRI");
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(0, 6, 6, 5);
        jPanel1.add(comboMetodePembayaran, gridBagConstraints);
    }

    private void setupTombolRiwayat() {
        JButton btnRiwayatPenjualan = new JButton("Riwayat Jual");
        JButton btnRiwayatRestok = new JButton("Riwayat Restok");
        btnRiwayatPenjualan.addActionListener(e -> tampilRiwayatPenjualan());
        btnRiwayatRestok.addActionListener(e -> tampilRiwayatRestok());
        GridBagConstraints gbcJual = new GridBagConstraints();
        gbcJual.gridx = 0;
        gbcJual.gridy = 13;
        gbcJual.gridwidth = 2;
        gbcJual.fill = GridBagConstraints.HORIZONTAL;
        gbcJual.insets = new Insets(6, 6, 6, 6);
        jPanel1.add(btnRiwayatPenjualan, gbcJual);
        GridBagConstraints gbcRestok = new GridBagConstraints();
        gbcRestok.gridx = 2;
        gbcRestok.gridy = 13;
        gbcRestok.gridwidth = 2;
        gbcRestok.fill = GridBagConstraints.HORIZONTAL;
        gbcRestok.insets = new Insets(6, 6, 6, 6);
        jPanel1.add(btnRiwayatRestok, gbcRestok);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void tampilBBM() {
        modeTabel = "DATA";
        selectedBbmId = 0;
        selectedHistoryId = 0;
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Kode", "Nama", "Harga Jual", "Stok"}, 0) { public boolean isCellEditable(int r, int c) { return false; } };
        for (BBM b : bbmDAO.getAllBBM(null)) model.addRow(new Object[]{b.getIdBbm(), b.getKodeBbm(), b.getNamaBbm(), b.getHargaJual(), b.getStok()});
        TbRiwayat.setModel(model);
    }

    private void tampilRiwayatPenjualan() {
        modeTabel = "PENJUALAN";
        selectedBbmId = 0;
        selectedHistoryId = 0;
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "No Transaksi", "Tanggal", "BBM", "Liter", "Harga Jual", "Total", "Metode", "Diterima", "Kembalian"}, 0) { public boolean isCellEditable(int r, int c) { return false; } };
        for (Object[] row : bbmDAO.getRiwayatPenjualan()) model.addRow(row);
        TbRiwayat.setModel(model);
    }

    private void tampilRiwayatRestok() {
        modeTabel = "RESTOK";
        selectedBbmId = 0;
        selectedHistoryId = 0;
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "No Transaksi", "Tanggal", "BBM", "Liter", "Harga Beli", "Total", "Akun", "Catatan"}, 0) { public boolean isCellEditable(int r, int c) { return false; } };
        for (Object[] row : bbmDAO.getRiwayatRestok()) model.addRow(row);
        TbRiwayat.setModel(model);
    }

    private void pilihBarisTabel() {
        int row = TbRiwayat.getSelectedRow();
        if (row < 0) return;
        if (!"DATA".equals(modeTabel)) {
            selectedHistoryId = Integer.parseInt(TbRiwayat.getValueAt(row, 0).toString());
            return;
        }
        selectedBbmId = Integer.parseInt(TbRiwayat.getValueAt(row, 0).toString());
        TxtID.setText(String.valueOf(selectedBbmId));
        TxtNama.setText(TbRiwayat.getValueAt(row, 2).toString());
        TxtHargaJual.setText(TbRiwayat.getValueAt(row, 3).toString());
        hitungTotal();
    }

    private void simpanPenjualan() {
        try {
            if (selectedBbmId <= 0) throw new Exception("BBM wajib dipilih dari tabel.");
            double liter = parseDouble(TxtLiter.getText());
            double hargaJual = parseDouble(TxtHargaJual.getText());
            String metode = comboMetodePembayaran.getSelectedItem() == null ? "" : comboMetodePembayaran.getSelectedItem().toString();
            if (liter <= 0) throw new Exception("Liter harus lebih dari 0.");
            if (hargaJual <= 0) throw new Exception("Harga jual harus lebih dari 0.");
            if (metode.isEmpty()) throw new Exception("Metode pembayaran wajib dipilih (Cash/BRI).");
            double total = liter * hargaJual;
            double diterima = metode.equalsIgnoreCase("Cash") ? parseDouble(TxtDiterima.getText()) : total;
            if (metode.equalsIgnoreCase("Cash") && diterima < total) throw new Exception("Uang diterima tidak boleh kurang dari total.");
            double kembali = metode.equalsIgnoreCase("Cash") ? diterima - total : 0;
            BBMPenjualan p = new BBMPenjualan();
            p.setTanggal(DatePickerHelper.requireSqlDate(TxtTgl, "Tanggal penjualan")); p.setUserId(Session.idUser); p.setBbmId(selectedBbmId);
            p.setLiter(liter); p.setHargaJual(hargaJual); p.setTotal(total); p.setMetodePembayaran(metode); p.setDiterima(diterima); p.setKembalian(kembali);
            bbmDAO.prosesPenjualan(p);
            JOptionPane.showMessageDialog(this, "Penjualan BBM berhasil disimpan: " + p.getNomorTransaksi());
            clearForm(); tampilRiwayatPenjualan();
        } catch (Exception e) { JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); }
    }

    private void hapusRiwayatTerpilih() {
        try {
if ("DATA".equals(modeTabel)) {
    hapusBBMModeData();
    return;
}

if (selectedHistoryId <= 0) {
    throw new Exception("Pilih baris riwayat penjualan/restok yang akan dihapus.");
}
            int confirm1 = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus transaksi BBM terpilih?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm1 != JOptionPane.YES_OPTION) return;
            int confirm2 = JOptionPane.showConfirmDialog(this, "Penghapusan akan mempengaruhi stok, saldo, harga beli rata-rata, dashboard, dan laporan. Lanjutkan?", "Peringatan Rollback", JOptionPane.YES_NO_OPTION);
            if (confirm2 != JOptionPane.YES_OPTION) return;
            if ("PENJUALAN".equals(modeTabel)) {
                bbmDAO.hapusPenjualanDenganRollback(selectedHistoryId);
                tampilRiwayatPenjualan();
            } else if ("RESTOK".equals(modeTabel)) {
                bbmDAO.hapusRestokDenganRollback(selectedHistoryId);
                tampilRiwayatRestok();
            }
            JOptionPane.showMessageDialog(this, "Transaksi BBM berhasil dihapus dan efek lama sudah di-rollback.");
        } catch (Exception e) { JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); }
    }

    private void hapusBBMModeData() throws Exception {
        if (selectedBbmId <= 0) throw new Exception("Pilih data BBM yang akan dihapus.");
        int confirm = JOptionPane.showConfirmDialog(this, "Hapus master BBM terpilih?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;
        if (!bbmDAO.hapusBBM(selectedBbmId)) throw new Exception("Gagal menghapus master BBM. Pastikan BBM belum dipakai transaksi.");
        JOptionPane.showMessageDialog(this, "Data BBM berhasil dihapus.");
        clearForm();
        tampilBBM();
    }

    private void hitungTotal() {
        try { double liter = parseDouble(TxtLiter.getText()); double harga = parseDouble(TxtHargaJual.getText()); TxtTotal.setText(String.valueOf(liter * harga)); } catch (Exception ignored) {}
    }
    private double parseDouble(String value) throws Exception { try { return Double.parseDouble(value.trim().replace(",", ".")); } catch (Exception e) { throw new Exception("Input angka tidak valid."); } }
    private void clearForm() { selectedBbmId = 0; selectedHistoryId = 0; TxtID.setText(""); TxtNoTransaksi.setText(""); TxtNama.setText(""); TxtLiter.setText(""); TxtHargaJual.setText(""); TxtTotal.setText(""); TxtPembayaran.setText(""); if (comboMetodePembayaran.getItemCount() > 0) comboMetodePembayaran.setSelectedIndex(0); TxtDiterima.setText(""); TxtKembalian.setText(""); DatePickerHelper.resetToToday(TxtTgl, DpTgl); TbRiwayat.clearSelection(); }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnData;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnRestok;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TbRiwayat;
    private javax.swing.JTextField TxtDiterima;
    private javax.swing.JTextField TxtHargaJual;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtKembalian;
    private javax.swing.JTextField TxtLiter;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNoTransaksi;
    private javax.swing.JTextField TxtPembayaran;
    private javax.swing.JFormattedTextField TxtTgl;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
