/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component;

import helper.RupiahFormat;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CartItem extends javax.swing.JPanel {

    /**
     * Creates new form MenuCard
     */
    private int idProduk;
    private String namaProduk;
    private double harga;
    private int qty = 1;
    private int stok;
    
    private Runnable onDelete;

    public CartItem(
        int idProduk,
        String namaProduk,
        double harga,
        int stok
) 
    {

    initComponents();
    
    setPreferredSize(new Dimension(200, 60));
    setMaximumSize(new Dimension(1700,60));
    this.idProduk = idProduk;
    this.namaProduk = namaProduk;
    this.harga = harga;
    this.stok=stok;

    refresh();
}
    
    private void refresh() {

    LblNama.setText(namaProduk);

    LblHarga.setText(
            RupiahFormat.format(harga)
    );

    TxtQty.setText(
            String.valueOf(qty)
    );  
}
    
    public int getIdProduk() {
    return idProduk;
}
    public String getNamaProduk() {
    return namaProduk;
}
    public int getQty() {
    return qty;
}
    public double getHarga() {
    return harga;
}
    public double getSubtotal() {
    return harga * qty;
}
    
    public void tambahQty() {
    if(qty >= stok){

    JOptionPane.showMessageDialog(
        this,
        "Stok tidak mencukupi"
        );

    return;
    }
    
    qty++;

    if(onQtyChanged != null){
        onQtyChanged.run();
        }
    
    refresh();
}
    
    public void kurangQty() {

    if(qty > 1){

        qty--;
        
        if(onQtyChanged != null){
        onQtyChanged.run();
        }
        
        refresh();
    }
}
    

    public void setOnDelete(Runnable onDelete) {
    this.onDelete = onDelete;
    
}
    
    private Runnable onQtyChanged;

    public void setOnQtyChanged(
            Runnable onQtyChanged
    ){
        this.onQtyChanged = onQtyChanged;
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        LblNama = new javax.swing.JLabel();
        LblHarga = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnMin = new javax.swing.JButton();
        TxtQty = new javax.swing.JLabel();
        BtnPlus = new javax.swing.JButton();
        BtnX = new javax.swing.JButton();

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        setLayout(new java.awt.GridBagLayout());

        LblNama.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        LblNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblNama.setText("Nama");
        LblNama.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LblNama.setName("LblNama"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        add(LblNama, gridBagConstraints);

        LblHarga.setFont(new java.awt.Font("Poppins ExtraBold", 0, 12)); // NOI18N
        LblHarga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblHarga.setText("Harga");
        LblHarga.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LblHarga.setName("LblHarga"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(LblHarga, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        BtnMin.setBackground(new java.awt.Color(0, 0, 0));
        BtnMin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BtnMin.setForeground(new java.awt.Color(255, 255, 255));
        BtnMin.setText("-");
        BtnMin.setName("BtnMin"); // NOI18N
        BtnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel3.add(BtnMin, gridBagConstraints);

        TxtQty.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        TxtQty.setText("Qty");
        TxtQty.setName("TxtQty"); // NOI18N
        jPanel3.add(TxtQty, new java.awt.GridBagConstraints());

        BtnPlus.setBackground(new java.awt.Color(0, 0, 0));
        BtnPlus.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BtnPlus.setForeground(new java.awt.Color(255, 255, 255));
        BtnPlus.setText("+");
        BtnPlus.setName("BtnPlus"); // NOI18N
        BtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jPanel3.add(BtnPlus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 6, 6);
        add(jPanel3, gridBagConstraints);

        BtnX.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BtnX.setText("x");
        BtnX.setAlignmentY(0.0F);
        BtnX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnX.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnX.setName("BtnX"); // NOI18N
        BtnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(BtnX, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinActionPerformed
        kurangQty();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMinActionPerformed

    private void BtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlusActionPerformed
        tambahQty();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPlusActionPerformed

    private void BtnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXActionPerformed
    if(onDelete != null){
        onDelete.run();
    }
// TODO add your handling code here:
    }//GEN-LAST:event_BtnXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMin;
    private javax.swing.JButton BtnPlus;
    private javax.swing.JButton BtnX;
    private javax.swing.JLabel LblHarga;
    private javax.swing.JLabel LblNama;
    private javax.swing.JLabel TxtQty;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
