/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component;

import helper.RupiahFormat;
import java.awt.Dimension;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class MenuCard extends javax.swing.JPanel {

    private int idProduk;
    private String namaProduk;
    private double harga;
    private int stok;

public MenuCard(
        int idProduk,
        String nama,
        String harga,
        String stok
) 
{

    this.idProduk = idProduk;

    initComponents();
    
    this.idProduk = idProduk;
    this.namaProduk = nama;
    this.harga = Double.parseDouble(harga);
    this.stok = Integer.parseInt(stok);

    lblNama.setText(nama);
    lblHarga.setText("Rp " + harga);
    lblHarga.setText(
    RupiahFormat.format(harga)
);
    lblStok.setText(stok);
    
    setPreferredSize(
    new Dimension(180, 64)
    );
    
    ProdukCard.putClientProperty(
                "FlatLaf.style",
                   "arc:12;"
                 + "border:2,2,2,2,@accentColor");
    
    PnlStok.putClientProperty(
                "FlatLaf.style",
                   "arc:12");
    
    setSelected(false);
}


    public int getIdProduk() {
    return idProduk;
    }

    public String getNamaProduk() {
    return namaProduk;
    }

    public double getHarga() {
    return harga;
    }
    
    public int getStok() {
    return stok;
    }

    public void setSelected(boolean selected){

    if(selected){

        ProdukCard.setBackground(Color.BLACK);

        lblNama.setForeground(Color.WHITE);
        lblHarga.setForeground(Color.WHITE);

        PnlStok.setBackground(Color.WHITE);
        lblStok.setForeground(Color.BLACK);

    }else{

        ProdukCard.setBackground(Color.WHITE);

        lblNama.setForeground(Color.BLACK);
        lblHarga.setForeground(Color.BLACK);

        PnlStok.setBackground(Color.BLACK);
        lblStok.setForeground(Color.WHITE);
    }

    repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ProdukCard = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        PnlStok = new javax.swing.JPanel();
        lblStok = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(160, 64));
        setLayout(new java.awt.GridBagLayout());

        ProdukCard.setBackground(new java.awt.Color(255, 255, 255));
        ProdukCard.setName("ProdukCard"); // NOI18N
        ProdukCard.setLayout(new java.awt.GridBagLayout());

        lblNama.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lblNama.setText("Sampoerna Mild 16");
        lblNama.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblNama.setName("lblNama"); // NOI18N
        lblNama.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        ProdukCard.add(lblNama, gridBagConstraints);

        lblHarga.setFont(new java.awt.Font("Poppins ExtraBold", 1, 14)); // NOI18N
        lblHarga.setText("Rp 32.000");
        lblHarga.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblHarga.setName("lblHarga"); // NOI18N
        lblHarga.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        ProdukCard.add(lblHarga, gridBagConstraints);

        PnlStok.setBackground(new java.awt.Color(0, 0, 0));
        PnlStok.setName("PnlStok"); // NOI18N
        PnlStok.setLayout(new java.awt.BorderLayout());

        lblStok.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblStok.setForeground(new java.awt.Color(255, 255, 255));
        lblStok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStok.setText("5");
        lblStok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblStok.setName("lblStok"); // NOI18N
        PnlStok.add(lblStok, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        ProdukCard.add(PnlStok, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.5;
        add(ProdukCard, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlStok;
    private javax.swing.JPanel ProdukCard;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStok;
    // End of variables declaration//GEN-END:variables
}
