/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.keuangan;

/**
 *
 * @author ASUS
 */
public
        class KeuanganPanel extends javax.swing.JPanel {

    /**
     * Creates new form KeuanganPanel
     */
    public KeuanganPanel() {
            initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header = new javax.swing.JPanel();
        inputForm = new javax.swing.JPanel();
        tipeKeuangan = new javax.swing.JTabbedPane();
        masuk = new javax.swing.JPanel();
        cbKat_In = new javax.swing.JComboBox<>();
        txtNominal_In = new javax.swing.JTextField();
        cbMet_In = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKet_In = new javax.swing.JTextArea();
        txtTgl_In = new javax.swing.JTextField();
        spacing = new javax.swing.JPanel();
        btnPanel = new javax.swing.JPanel();
        btnSimpan_In = new javax.swing.JButton();
        btnClear_In = new javax.swing.JButton();
        keluar = new javax.swing.JPanel();
        cbKat_Out = new javax.swing.JComboBox<>();
        txtNominal_Out = new javax.swing.JTextField();
        cbMet_Out = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKet_Out = new javax.swing.JTextArea();
        txtTgl_Out = new javax.swing.JTextField();
        btnPanel1 = new javax.swing.JPanel();
        btnSimpan_In1 = new javax.swing.JButton();
        btnClear_In1 = new javax.swing.JButton();
        spacing1 = new javax.swing.JPanel();
        transfer = new javax.swing.JPanel();
        cbFrom = new javax.swing.JComboBox<>();
        cbTo = new javax.swing.JComboBox<>();
        txtNominal_Tf = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtKet_Tf = new javax.swing.JTextArea();
        btnPanel2 = new javax.swing.JPanel();
        btnSimpan_In2 = new javax.swing.JButton();
        btnClear_In2 = new javax.swing.JButton();
        spacing2 = new javax.swing.JPanel();
        tableArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(java.awt.Color.green);
        setLayout(new java.awt.BorderLayout(12, 12));

        header.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        header.setName("header"); // NOI18N
        header.setPreferredSize(new java.awt.Dimension(400, 60));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        add(header, java.awt.BorderLayout.NORTH);

        inputForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        inputForm.setName("inputForm"); // NOI18N
        inputForm.setPreferredSize(new java.awt.Dimension(300, 0));
        inputForm.setLayout(new java.awt.BorderLayout());

        tipeKeuangan.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tipeKeuangan.setName("tipeKeuangan"); // NOI18N

        masuk.setBackground(new java.awt.Color(230, 230, 230));
        masuk.setAlignmentY(0.0F);
        masuk.setName("masuk"); // NOI18N
        java.awt.GridBagLayout masukLayout = new java.awt.GridBagLayout();
        masukLayout.columnWeights = new double[] {0.1, 0.1, 0.1};
        masuk.setLayout(masukLayout);

        cbKat_In.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKat_In.setName("cbKat_In"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        masuk.add(cbKat_In, gridBagConstraints);

        txtNominal_In.setText("Nominal");
        txtNominal_In.setName("txtNominal_In"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        masuk.add(txtNominal_In, gridBagConstraints);

        cbMet_In.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMet_In.setName("cbMet_In"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        masuk.add(cbMet_In, gridBagConstraints);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtKet_In.setColumns(20);
        txtKet_In.setRows(5);
        txtKet_In.setName("txtKet_In"); // NOI18N
        jScrollPane2.setViewportView(txtKet_In);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        masuk.add(jScrollPane2, gridBagConstraints);

        txtTgl_In.setText("Tanggal");
        txtTgl_In.setName("txtTgl_In"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        masuk.add(txtTgl_In, gridBagConstraints);

        spacing.setName("spacing"); // NOI18N
        spacing.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        masuk.add(spacing, gridBagConstraints);

        btnPanel.setName("btnPanel"); // NOI18N
        btnPanel.setLayout(new java.awt.GridBagLayout());

        btnSimpan_In.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan_In.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan_In.setText("Konfirmasi");
        btnSimpan_In.setName("btnSimpan_In"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 8, 12);
        btnPanel.add(btnSimpan_In, gridBagConstraints);

        btnClear_In.setBackground(new java.awt.Color(0, 0, 0));
        btnClear_In.setForeground(new java.awt.Color(255, 255, 255));
        btnClear_In.setText("Clear");
        btnClear_In.setName("btnClear_In"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 8, 12);
        btnPanel.add(btnClear_In, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        masuk.add(btnPanel, gridBagConstraints);

        tipeKeuangan.addTab("Pemasukan", masuk);

        keluar.setName("keluar"); // NOI18N
        java.awt.GridBagLayout keluarLayout = new java.awt.GridBagLayout();
        keluarLayout.columnWeights = new double[] {0.1, 0.1, 0.1};
        keluar.setLayout(keluarLayout);

        cbKat_Out.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKat_Out.setName("cbKat_Out"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        keluar.add(cbKat_Out, gridBagConstraints);

        txtNominal_Out.setText("Nominal");
        txtNominal_Out.setName("txtNominal_Out"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        keluar.add(txtNominal_Out, gridBagConstraints);

        cbMet_Out.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMet_Out.setName("cbMet_Out"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        keluar.add(cbMet_Out, gridBagConstraints);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        txtKet_Out.setColumns(20);
        txtKet_Out.setRows(5);
        txtKet_Out.setName("txtKet_Out"); // NOI18N
        jScrollPane3.setViewportView(txtKet_Out);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        keluar.add(jScrollPane3, gridBagConstraints);

        txtTgl_Out.setText("Tanggal");
        txtTgl_Out.setName("txtTgl_Out"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        keluar.add(txtTgl_Out, gridBagConstraints);

        btnPanel1.setName("btnPanel1"); // NOI18N
        btnPanel1.setLayout(new java.awt.GridBagLayout());

        btnSimpan_In1.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan_In1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan_In1.setText("Konfirmasi");
        btnSimpan_In1.setName("btnSimpan_In1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 8, 12);
        btnPanel1.add(btnSimpan_In1, gridBagConstraints);

        btnClear_In1.setBackground(new java.awt.Color(0, 0, 0));
        btnClear_In1.setForeground(new java.awt.Color(255, 255, 255));
        btnClear_In1.setText("Clear");
        btnClear_In1.setName("btnClear_In1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 8, 12);
        btnPanel1.add(btnClear_In1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        keluar.add(btnPanel1, gridBagConstraints);

        spacing1.setName("spacing1"); // NOI18N
        spacing1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        keluar.add(spacing1, gridBagConstraints);

        tipeKeuangan.addTab("Pengeluaran", keluar);

        transfer.setName("transfer"); // NOI18N
        java.awt.GridBagLayout transferLayout = new java.awt.GridBagLayout();
        transferLayout.columnWeights = new double[] {0.1, 0.1, 0.1};
        transfer.setLayout(transferLayout);

        cbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFrom.setName("cbFrom"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        transfer.add(cbFrom, gridBagConstraints);

        cbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTo.setName("cbTo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 12);
        transfer.add(cbTo, gridBagConstraints);

        txtNominal_Tf.setText("Nominal");
        txtNominal_Tf.setName("txtNominal_Tf"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        transfer.add(txtNominal_Tf, gridBagConstraints);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        txtKet_Tf.setColumns(20);
        txtKet_Tf.setRows(5);
        txtKet_Tf.setName("txtKet_Tf"); // NOI18N
        jScrollPane4.setViewportView(txtKet_Tf);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        transfer.add(jScrollPane4, gridBagConstraints);

        btnPanel2.setName("btnPanel2"); // NOI18N
        btnPanel2.setLayout(new java.awt.GridBagLayout());

        btnSimpan_In2.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan_In2.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan_In2.setText("Konfirmasi");
        btnSimpan_In2.setName("btnSimpan_In2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 8, 12);
        btnPanel2.add(btnSimpan_In2, gridBagConstraints);

        btnClear_In2.setBackground(new java.awt.Color(0, 0, 0));
        btnClear_In2.setForeground(new java.awt.Color(255, 255, 255));
        btnClear_In2.setText("Clear");
        btnClear_In2.setName("btnClear_In2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 8, 12);
        btnPanel2.add(btnClear_In2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        transfer.add(btnPanel2, gridBagConstraints);

        spacing2.setName("spacing2"); // NOI18N
        spacing2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        transfer.add(spacing2, gridBagConstraints);

        tipeKeuangan.addTab("Transfer", transfer);

        inputForm.add(tipeKeuangan, java.awt.BorderLayout.PAGE_START);

        add(inputForm, java.awt.BorderLayout.EAST);

        tableArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tableArea.setName("tableArea"); // NOI18N
        tableArea.setPreferredSize(new java.awt.Dimension(700, 1200));
        tableArea.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setRowHeaderView(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        tableArea.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(tableArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear_In;
    private javax.swing.JButton btnClear_In1;
    private javax.swing.JButton btnClear_In2;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel btnPanel1;
    private javax.swing.JPanel btnPanel2;
    private javax.swing.JButton btnSimpan_In;
    private javax.swing.JButton btnSimpan_In1;
    private javax.swing.JButton btnSimpan_In2;
    private javax.swing.JComboBox<String> cbFrom;
    private javax.swing.JComboBox<String> cbKat_In;
    private javax.swing.JComboBox<String> cbKat_Out;
    private javax.swing.JComboBox<String> cbMet_In;
    private javax.swing.JComboBox<String> cbMet_Out;
    private javax.swing.JComboBox<String> cbTo;
    private javax.swing.JPanel header;
    private javax.swing.JPanel inputForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel keluar;
    private javax.swing.JPanel masuk;
    private javax.swing.JPanel spacing;
    private javax.swing.JPanel spacing1;
    private javax.swing.JPanel spacing2;
    private javax.swing.JPanel tableArea;
    private javax.swing.JTabbedPane tipeKeuangan;
    private javax.swing.JPanel transfer;
    private javax.swing.JTextArea txtKet_In;
    private javax.swing.JTextArea txtKet_Out;
    private javax.swing.JTextArea txtKet_Tf;
    private javax.swing.JTextField txtNominal_In;
    private javax.swing.JTextField txtNominal_Out;
    private javax.swing.JTextField txtNominal_Tf;
    private javax.swing.JTextField txtTgl_In;
    private javax.swing.JTextField txtTgl_Out;
    // End of variables declaration//GEN-END:variables
}



