/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.main;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JFrame;
import config.Koneksi;
import helper.AlertHelper;
import java.awt.Toolkit;
import session.Session;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author ASUS
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/shop.png")));
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        TxtUser.putClientProperty("FlatLaf.style", "showClearButton:true");
        
        BtnClear.putClientProperty(
                "FlatLaf.style",
                   "arc:12;"
                 + "foreground:#000000;"
                 + "background:#ffffff"
            );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        flatDarkLaf1 = new com.formdev.flatlaf.FlatDarkLaf();
        swingUtils1 = new com.formdev.flatlaf.util.SwingUtils();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TxtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        BtnClear = new javax.swing.JButton();
        BtnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        TxtPass.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        TxtPass.setName("TxtPass"); // NOI18N
        TxtPass.setNextFocusableComponent(BtnLogin);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel2.add(TxtPass, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setText("Username");
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel2.add(jLabel3, gridBagConstraints);

        TxtUser.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        TxtUser.setName("TxtUser"); // NOI18N
        TxtUser.setNextFocusableComponent(TxtPass);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        jPanel2.add(TxtUser, gridBagConstraints);

        BtnClear.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.setContentAreaFilled(false);
        BtnClear.setName("BtnClear"); // NOI18N
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(BtnClear, gridBagConstraints);

        BtnLogin.setBackground(new java.awt.Color(0, 0, 0));
        BtnLogin.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.setName("BtnLogin"); // NOI18N
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(BtnLogin, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setText("Login");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 450, 0, 450);
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        prosesLogin();
//        demoLogin();        
// TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnClearActionPerformed

//    Login demo
     private void demoLogin() {
        String username = TxtUser.getText();
        String password = TxtPass.getText();

        if (username.equals("tian") && password.equals("1111")) {

            JOptionPane.showMessageDialog(this, "Login Berhasil");

            MainFrame main = new MainFrame();
            main.setVisible(true);

            this.dispose();

        } else {

            JOptionPane.showMessageDialog(this, "Username atau Password Salah");

        }

     }
     
//     Login beneran
    private void prosesLogin() {
        String user = TxtUser.getText().trim();
        String pass = new String(TxtPass.getPassword()).trim();

        // Validasi input kosong
        if (user.isEmpty() || pass.isEmpty()) {
            AlertHelper.showMessage("Masukkan Username dan Password");
            return;
        }

        // Query cek user
        String sql = "SELECT id_user, username, nama FROM tb_user WHERE username = ? AND password = ?";
        try (Connection conn = Koneksi.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, user);
            ps.setString(2, pass);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Simpan session
                Session.idUser = rs.getInt("id_user");
                Session.username = rs.getString("username");
                Session.namaUser = rs.getString("nama");

                AlertHelper.showMessage("Berhasil Login. Selamat Datang");

                // Buka MainFrame
                MainFrame mainFrame = new MainFrame();
                setExtendedState(JFrame.MAXIMIZED_BOTH);
                mainFrame.setVisible(true);
                // Tutup LoginFrame
                this.dispose();
            } else {
                AlertHelper.showMessage("Login Gagal. Username atau Password salah");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
        null,
        ex.getMessage(),
        "SQL Error",
        JOptionPane.ERROR_MESSAGE
    );
    ex.printStackTrace();
        }
    }
    
    private void bersih() {
        TxtUser.setText("");
        TxtPass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    FlatLaf.registerCustomDefaultsSource("theme");

    FlatLightLaf.setup();
        
    java.awt.EventQueue.invokeLater(() -> {
    new LoginFrame().setVisible(true);
    }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JTextField TxtUser;
    private com.formdev.flatlaf.FlatDarkLaf flatDarkLaf1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.formdev.flatlaf.util.SwingUtils swingUtils1;
    // End of variables declaration//GEN-END:variables
}
