/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.main;


import com.formdev.flatlaf.*;
import helper.FontIcon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import view.bbm.BBMPanel;
import view.brilink.BRILinkPanel;
import view.dashboard.DashboardPanel;
import view.keuangan.KeuanganPanel;
import view.laporan.LaporanPanel;
import view.penjualan.PenjualanPanel;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.*;


/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
  
    
    
    public MainFrame() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/shop.png")));
        
        initComponents();
        
    //  Load All Panel     
        Home.setLayout(new BorderLayout());
        Home.add(new DashboardPanel(), BorderLayout.CENTER);

        BRILink.setLayout(new BorderLayout());
        BRILink.add(new BRILinkPanel(),BorderLayout.CENTER);

        BBM.setLayout(new BorderLayout());
        BBM.add(new BBMPanel(),BorderLayout.CENTER);

        Penjualan.setLayout(new BorderLayout());
        Penjualan.add(new PenjualanPanel(),BorderLayout.CENTER);

        Keuangan.setLayout(new BorderLayout());
        Keuangan.add(new KeuanganPanel(), BorderLayout.CENTER);
        
        Laporan.setLayout(new BorderLayout());
        Laporan.add(new LaporanPanel(),BorderLayout.CENTER);
        
        // Load Icon
        Font outlinedFont, filledFont;
        try (InputStream isOutlined = getClass().getResourceAsStream("/assets/fonts/MaterialIconsOutlined-Regular.otf");
             InputStream isFilled = getClass().getResourceAsStream("/assets/fonts/MaterialIcons-Regular.ttf")) {
            outlinedFont = Font.createFont(Font.TRUETYPE_FONT, isOutlined);
            filledFont = Font.createFont(Font.TRUETYPE_FONT, isFilled);
        } catch (Exception e) {
            e.printStackTrace();
            outlinedFont = new Font("Segoe UI", Font.PLAIN, 18);
            filledFont = outlinedFont;
        }
        
        final Font finalOutlinedFont = outlinedFont;
        final Font finalFilledFont = filledFont;
        
        FontIcon[] icons = {
            new FontIcon("\uE88A", finalOutlinedFont.deriveFont(18f), Color.BLUE, 24, 24), // Home
            new FontIcon("\uE8CC", finalOutlinedFont.deriveFont(18f), Color.BLUE, 24, 24), // Penjualan
            new FontIcon("\uE546", finalOutlinedFont.deriveFont(18f), Color.BLUE, 24, 24), // BBM
            new FontIcon("\uE84F", finalOutlinedFont.deriveFont(18f), Color.BLUE, 24, 24), // BRILink
            new FontIcon("\uE227", finalOutlinedFont.deriveFont(18f), Color.BLUE, 24, 24), // Keuangan
            new FontIcon("\uE915", finalOutlinedFont.deriveFont(18f), Color.BLUE, 24, 24)  // Laporan
        };

        for (int i = 0; i < icons.length; i++) {
            sidebarTabs.setIconAt(i, icons[i]);
        }

        sidebarTabs.addChangeListener(e -> {
            int selectedIndex = sidebarTabs.getSelectedIndex();

            // Perbarui ikon: tab aktif → Filled, lainnya → Outlined
            for (int i = 0; i < icons.length; i++) {
                FontIcon icon = icons[i];
                if (i == selectedIndex) {
                    icon.setFont(finalFilledFont.deriveFont(18f));
                } else {
                    icon.setFont(finalOutlinedFont.deriveFont(18f));
                }
            }sidebarTabs.repaint();
        }
        );
        
        sidebarTabs.setSelectedIndex(0);
        icons[0].setFont(finalFilledFont.deriveFont(18f));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        sidebarTabs = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        BRILink = new javax.swing.JPanel();
        BBM = new javax.swing.JPanel();
        Penjualan = new javax.swing.JPanel();
        Keuangan = new javax.swing.JPanel();
        Laporan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout(0, 5));

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setMinimumSize(new java.awt.Dimension(1000, 40));
        Header.setName("Header"); // NOI18N
        Header.setPreferredSize(new java.awt.Dimension(1000, 40));

        lblMenu.setForeground(java.awt.Color.white);
        lblMenu.setText("Menu");
        lblMenu.setName("lblMenu"); // NOI18N

        lblUser.setForeground(java.awt.Color.white);
        lblUser.setText("User");
        lblUser.setName("lblUser"); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu)
                    .addComponent(lblUser))
                .addContainerGap())
        );

        jPanel4.add(Header, java.awt.BorderLayout.NORTH);

        sidebarTabs.setBackground(java.awt.Color.black);
        sidebarTabs.setForeground(java.awt.Color.white);
        sidebarTabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        sidebarTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebarTabs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sidebarTabs.setName("sidebarTabs"); // NOI18N
        sidebarTabs.setOpaque(true);
        sidebarTabs.setPreferredSize(new java.awt.Dimension(140, 2000));

        Home.setBackground(new java.awt.Color(51, 51, 51));
        Home.setForeground(new java.awt.Color(255, 0, 0));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home.setName("Home"); // NOI18N
        Home.setPreferredSize(new java.awt.Dimension(8, 372));

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        sidebarTabs.addTab("Home", Home);

        BRILink.setBackground(new java.awt.Color(51, 51, 51));
        BRILink.setForeground(new java.awt.Color(255, 0, 0));
        BRILink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BRILink.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BRILink.setName("BRILink"); // NOI18N
        BRILink.setPreferredSize(new java.awt.Dimension(8, 372));

        javax.swing.GroupLayout BRILinkLayout = new javax.swing.GroupLayout(BRILink);
        BRILink.setLayout(BRILinkLayout);
        BRILinkLayout.setHorizontalGroup(
            BRILinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        BRILinkLayout.setVerticalGroup(
            BRILinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        sidebarTabs.addTab("BRILink", BRILink);

        BBM.setBackground(new java.awt.Color(51, 51, 51));
        BBM.setForeground(new java.awt.Color(255, 0, 0));
        BBM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BBM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BBM.setName("BBM"); // NOI18N
        BBM.setPreferredSize(new java.awt.Dimension(8, 372));

        javax.swing.GroupLayout BBMLayout = new javax.swing.GroupLayout(BBM);
        BBM.setLayout(BBMLayout);
        BBMLayout.setHorizontalGroup(
            BBMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BBMLayout.setVerticalGroup(
            BBMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        sidebarTabs.addTab("BBM", BBM);

        Penjualan.setBackground(new java.awt.Color(51, 51, 51));
        Penjualan.setForeground(new java.awt.Color(255, 0, 0));
        Penjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Penjualan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penjualan.setName("Penjualan"); // NOI18N
        Penjualan.setPreferredSize(new java.awt.Dimension(8, 372));

        javax.swing.GroupLayout PenjualanLayout = new javax.swing.GroupLayout(Penjualan);
        Penjualan.setLayout(PenjualanLayout);
        PenjualanLayout.setHorizontalGroup(
            PenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PenjualanLayout.setVerticalGroup(
            PenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        sidebarTabs.addTab("Penjualan", Penjualan);

        Keuangan.setBackground(new java.awt.Color(51, 51, 51));
        Keuangan.setForeground(new java.awt.Color(255, 0, 0));
        Keuangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Keuangan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Keuangan.setName("Keuangan"); // NOI18N
        Keuangan.setPreferredSize(new java.awt.Dimension(8, 372));

        javax.swing.GroupLayout KeuanganLayout = new javax.swing.GroupLayout(Keuangan);
        Keuangan.setLayout(KeuanganLayout);
        KeuanganLayout.setHorizontalGroup(
            KeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        KeuanganLayout.setVerticalGroup(
            KeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        sidebarTabs.addTab("Keuangan", Keuangan);

        Laporan.setBackground(new java.awt.Color(51, 51, 51));
        Laporan.setForeground(new java.awt.Color(255, 0, 0));
        Laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Laporan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Laporan.setName("Laporan"); // NOI18N
        Laporan.setPreferredSize(new java.awt.Dimension(8, 372));

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        sidebarTabs.addTab("Laporan", Laporan);

        sidebarTabs.setSelectedComponent(Home);

        jPanel4.add(sidebarTabs, java.awt.BorderLayout.CENTER);
        sidebarTabs.getAccessibleContext().setAccessibleName("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    FlatLaf.registerCustomDefaultsSource("theme");

    FlatLightLaf.setup();
        
    java.awt.EventQueue.invokeLater(() -> {
    new MainFrame().setVisible(true);
    }); 
}

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BBM;
    private javax.swing.JPanel BRILink;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Keuangan;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Penjualan;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTabbedPane sidebarTabs;
    // End of variables declaration//GEN-END:variables
}
